# This is a basic workflow to help you get started with Actions

name: Dev_workflow_externalapi
env:
  MY_FNAME: gaurav
  MY_LNAME: verma
  PROJECT_PATH: '/home/runner/work'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]

permissions:
  id-token: write    # This is required for OIDC authentication
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: lable-mylaptop
    environment:
      name: dev
    steps:
      - name: Login to Azure
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      - name: Get secrets from Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          vaultName: "gauravkvtest"
          secretNames: "FName, LNamenew"

      - name: Use the secrets in your workflow
        run: |
          echo "Secret 1 value: ${{ secrets.FName }}"          
          echo "Secret 2 value: ${{ secrets.LNamenew }}"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: checkout Code
        with:
          sparse-checkout: 'external_api'  # Specify the desired folder
          sparse-checkout-cone-mode: false
          repository: ${{github.repository}}
          path: 'hybris_pipeline_external_api'

      - name: Setup and Run Pipeline
        working-directory: "D:\\Work_2\\actions-runner\\_work\\PracticeGithubActions\\PracticeGithubActions\\hybris_pipeline_external_api"
        run: |
          echo Setup and Run Pipeline
          python -m venv venv
          cd venv/Scripts
          .\activate
          cd..
          cd..
          cd 'Tool\\external_api'
          python newpythonfile.py
            

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello- ${{ vars.MY_ENV_FULL_DESC }}!. you are with secret ${{ secrets.SECRET1 }}. ${{env.MY_FNAME}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project, repository ${{github.repository}}.
